package com.jpmc.assignments.simplestock.exception;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

/**
 * Handler to work on the exceptions generated by SimpleStock Application
 * 
 * @author jnair1
 *
 */
@ControllerAdvice
public class SimpleStockExceptionHandler {
	
	@ExceptionHandler(SimpleStockException.class)
	public ResponseEntity<SimpleStockExceptionResponse> applicationExceptionHandler(Exception ex) {
		SimpleStockExceptionResponse error = new SimpleStockExceptionResponse();
		error.setErrorCode(HttpStatus.NOT_FOUND.value());
		error.setMessage(ex.getMessage());
		return new ResponseEntity<SimpleStockExceptionResponse>(error, HttpStatus.NOT_FOUND);
	}
	
	@ExceptionHandler(Exception.class)
	public ResponseEntity<SimpleStockExceptionResponse> exceptionHandler(Exception ex) {
		SimpleStockExceptionResponse error = new SimpleStockExceptionResponse();
		error.setErrorCode(HttpStatus.BAD_REQUEST.value());
		error.setMessage("Application failed to understand the request ");
		return new ResponseEntity<SimpleStockExceptionResponse>(error, HttpStatus.BAD_REQUEST);
	}
	
	
	@ExceptionHandler(IllegalArgumentException.class)
	public ResponseEntity<SimpleStockExceptionResponse> validationExceptionHandler(Exception ex) {
		SimpleStockExceptionResponse error = new SimpleStockExceptionResponse();
		error.setErrorCode(HttpStatus.BAD_REQUEST.value());
		error.setMessage("Validation failed" + ex.getMessage());
		return new ResponseEntity<SimpleStockExceptionResponse>(error, HttpStatus.BAD_REQUEST);
	}
}
